/** Shared user help and AI guidance. Runtime metadata only; no saved schema changes. */
export const authoringGuide = [
 { id: 'book-covers', selector: '[onclick="openProjectSettings()"]', related: ['book-pages', 'book-print'],
   ja: ['表紙・裏表紙の構成', '表紙ありではC1が表紙、C2が表紙の裏、C3が裏表紙の内側、C4が裏表紙です。役割は内容ではなくページの位置で決まります。', 'プロジェクト設定で表紙の有無を確認します。4ページ以上では先頭がC1、2ページ目がC2、最後から2ページ目がC3、末尾がC4です。2ページではC1とC4だけです。', '本文だけを書いても先頭・末尾が表紙扱いになる場合があります。追加・削除や再組版の後は、各言語の表紙位置を確認してください。', '', '表1 表2 表3 表4 C1 C2 C3 C4 表紙 裏表紙'],
   en: ['Front and back covers', 'With covers enabled, C1 is the front cover, C2 its inside, C3 the inside back cover, and C4 the back cover. Roles are determined by position, not content.', 'Check covers in Project settings. For 4 or more pages: first=C1, second=C2, penultimate=C3, last=C4. A 2-page work has C1 and C4 only.', 'Text-only pages may occupy cover positions. Check cover positions in each language after insertion, deletion or repagination.', '', 'cover C1 C2 C3 C4'] },
 { id: 'book-pages', selector: '[onclick="openProjectSettings()"]', related: ['book-covers', 'book-print'],
   ja: ['電子版のページ数・言語', '表紙ありの電子作品は2ページ以上の偶数ページです。4の倍数は必須ではありません。表紙なしにはこの偶数条件はありません。', '表紙も総ページ数に含めます。例えば14ページの電子作品は偶数条件を満たします。Flowは文章量と組版からページを生成するため、段落数とページ数は一致しません。', '原文言語は日本語に限りません。本文言語、縦横書き、ページ送り方向とUI言語は区別します。翻訳版はページ数が異なるため、言語ごとに組版後の構成を確認します。', '', '偶数 4ページ 4の倍数 ページ数 原文 多言語'],
   en: ['Digital page counts and languages', 'A digital work with covers requires an even total of at least 2 pages, not necessarily a multiple of 4. The coverless mode has no cover parity requirement.', 'Count covers in the total. A 14-page digital work satisfies parity. Flow generates pages from text and typography; paragraph count is not page count.', 'Any supported language can be the source. Content language, writing mode, page direction and interface language are separate. Translations may have different page counts; inspect each language after layout.', '', 'even multiple four pages source translation'] },
 { id: 'book-print', selector: '#ribbon-print', related: ['book-covers', 'print'],
   ja: ['冊子印刷と補完白紙', '二つ折り・中綴じ印刷では、表紙を含めた印刷ページ数を4の倍数にします。電子作品を常に4ページ単位で作る必要はありません。', '14ページなら印刷時に白紙2ページを補い16ページにします。全ページ・表紙ありではC3の前が既定で、C4の前も選べます。C4の前に入れると最後の補完白紙が印刷上のC3になります。', 'C1/C4だけの作品はC4の前、表紙なし・一部ページの印刷は選択末尾に補完します。印刷の白紙は元原稿を変更しません。両面設定はプレビューとプリンターで確認してください。', '', '中綴じ 二つ折り 面付け 白紙 補完 4の倍数'],
   en: ['Booklet printing and blank padding', 'Folded saddle-stitch printing needs a multiple of 4 pages including covers. Digital authoring does not always need multiples of 4.', 'For 14 pages, printing adds 2 blanks to make 16. For a full work with all four covers, padding defaults to before C3; before C4 is also available. Before-C4 padding makes the last inserted blank the printed C3.', 'Outer-cover-only works pad before C4. Coverless works and partial selections pad at the end. Print padding does not change the manuscript. Check preview and printer duplex settings.', '', 'booklet saddle stitch blanks padding'] },
 { id: 'book-layout', selector: '#btn-editor-preview', related: ['book-pages', 'preview'],
   ja: ['固定レイアウトと画像素材', 'DSFは9:16を基本とする固定レイアウトです。端末に合わせて文字が折り返される電子書籍とは異なり、Studioで決めたページを配信します。', 'Flowは本文を組版して固定ページにします。表紙画像などはページ比率を意識して用意し、画像素材やコピーした画像から画像ページを追加します。画像はクライアントでWebPに変換されます。', 'AIの画像生成とDSFへの画像受け渡しは別です。接続AIが実画像データを渡せない場合は、利用者がアップロード／貼り付けしてください。生成したと主張するだけでは画像を取り込めません。本文の文字を画像に置き換える必要はありません。', '', '9:16 固定レイアウト 画像 WebP 表紙 比率'],
   en: ['Fixed layout and image assets', 'DSF uses fixed layout, based on 9:16 pages. Studio determines the delivered page layout; the Viewer does not reflow text to fit the device.', 'Flow composes text into fixed pages. Prepare cover artwork with the page aspect ratio in mind and add image pages from imported assets or copied images. Images are converted to WebP on the client.', 'AI image generation and transfer to DSF are separate capabilities. If the client cannot transfer actual image bytes, ask the user to upload or paste them. Never invent image bytes. Text does not need to be replaced by raster images.', '', '9:16 fixed layout image WebP cover aspect ratio'] },
 { id: 'ai-authoring', selector: '[data-studio-ai]', related: ['book-covers', 'book-pages', 'publish'],
   ja: ['AIによる制作の確認事項', 'AIは制作前と変更後に作品構成を確認します。AI連携をオンにし、「AIに許可する操作」で「閲覧のみ」または「閲覧・編集」を選びます。', 'AIへ「WebMCPで編集状態と作品構成を取得し、原文言語・ページ送り方向・C1〜C4と本文の区分を確認してから制作して」と依頼できます。画像は素材または実画像データから取り込み、クライアントでWebPに変換します。', '組版中・未生成のページ数は未確定です。原文代替表示は翻訳完成ではありません。既存内容を読んでから編集し、変更後に再取得してください。AI設定はこのブラウザーで保持します。新規作品作成・作品切り替え後は新しい編集対象と操作用トークンを取得します。発行はプレスで検証しWorksで公開します。AIの発行操作は未提供です。', '', 'WebMCP AI Claude Gemini ChatGPT 制作'],
   en: ['AI authoring checks', 'AI should inspect composition before authoring and after changes. Turn on AI connection and choose Read only or Read and edit under AI access.', 'Ask AI to read editor context and book composition, then check source language, page direction, covers C1–C4 and body pages before authoring. Import actual image assets or image bytes; conversion to WebP happens on the client.', 'Pending or ungenerated pagination is unknown. Source fallback is not a completed translation. Read existing content before edits and read back afterward. AI access is saved in this browser. After project creation or switching, obtain fresh editor context and operation tokens. Validate in Press and publish from Works; AI publishing is not exposed.', '', 'WebMCP AI Claude Gemini ChatGPT'] }
];
authoringGuide.push({ id: 'ai-page-operations', selector: '[data-studio-ai]', related: ['book-covers', 'ai-authoring'],
 ja: ['AIによるページの選択・並べ替え', '既存の表紙を移すときは、削除・再追加ではなくページ移動を使います。右綴じでも先頭・末尾は読書順で指定します。', 'AIはページ構成と操作単位の一覧を読み、必要ならページを選択します。並べ替えと画像差し替えは対象・配置を準備してから適用します。1回の元に戻すで取り消せます。', 'Flow原稿と見開きは全体を移動します。Flow生成ページを単独で移動・画像置換しません。画像差し替えは単独の画像ページと取り込み済みWebP素材が対象です。C1〜C4は位置に応じて変わるため、操作後に各言語の構成を再確認します。', '', 'AI ページ 移動 並べ替え 表紙 選択 差し替え WebMCP'],
 en: ['AI page selection and ordering', 'Move an existing cover instead of deleting and re-adding it. Start/end always mean reading order, including right binding.', 'Read dsf_get_book_composition and dsf_list_page_units. Use dsf_select_page for selection, dsf_prepare_page_move or dsf_prepare_image_replacement to inspect a plan, then dsf_apply_page_change. Mutations create one Undo step.', 'Move Flow manuscripts and spreads whole, not individual generated pages. Replacement accepts one fixed image page and an imported WebP asset. It preserves page ID and overlays and resets current-language positioning. Recheck C1-C4 and all language compositions after layout. No page deletion or publication is exposed.', '', 'AI page move reorder select cover replace WebMCP'] });
export function getAIAuthoringGuide() {
 return authoringGuide.map(({id,en}) => ({id, title:en[0], rule:en[1], workflow:en[2], constraints:en[3]}));
}
