import {createPlatformNavigator} from './platform-navigation.js';
import {getPlatformLanguage,setPlatformLanguage,subscribePlatformLanguage,UI_LANGUAGES} from './ui-language.js';
import {installPlatformLaunchNotice} from './platform-launch-ui.js';
import {getThemeMode,setThemeMode} from './theme.js';
import '../css/platform-menu.css';
const copy={ja:{title:'Horizonメニュー',close:'閉じる',portal:'リードを探す — Horizon',studio:'リードをつくる — Studio',viewer:'リードを読むアプリ — Reader',settings:'アプリの設定',language:'メニューの言語',languageHelp:'Horizon・Studio・Readerで共通です。リード本文の言語は変わりません。',theme:'配色',device:'端末に合わせる',light:'ライト',dark:'ダーク',glossary:'Horizonの用語',glossaryHelp:'リード（Read）はDSFで作成・公開される1つのコンテンツ、リーズ（Reads）はその複数形です。小説、観光パンフレット、漫画、ノートなどを含みます。Studioは作成・編集、Readerは読むための標準環境、Horizonは探す・公開する・集める場所です。',help:'使い方',portalHelp:'公開リーズを検索して開きます。リードの言語は、読書画面の「i」から選べます。',studioHelp:'ダッシュボードで原稿を選び、エディターで編集し、プレスから発行します。リードの言語はプロジェクト設定で管理します。',viewerHelp:'左右へのスワイプや矢印でページを送ります。ページ中央をタップすると操作ボタンが表示されます。「表示」は読み方、「i」はリード情報とリードの言語です。',separate:'通常の移動はこのウィンドウで開きます。編集中の原稿は保存してから移動してください。',file:'この端末のファイルを開く',home:'ダッシュボード',editor:'エディター',press:'プレス',works:'リーズ',guide:'Studioの操作ヘルプ',development:'開発プレビューではアプリの更新を確認しません。'},en:{title:'Horizon menu',close:'Close',portal:'Explore Reads — Horizon',studio:'Create Read — Studio',viewer:'Reading app — Reader',settings:'App settings',language:'Menu language',languageHelp:'Shared by Horizon, Studio and Reader. This does not change the language of a Read.',theme:'Appearance',device:'Use device setting',light:'Light',dark:'Dark',glossary:'Horizon terminology',glossaryHelp:'A Read is one item created and published with DSF; Reads is the plural. Reads include novels, travel guides, comics and notes. Studio is for creating and editing; Reader is the standard reading environment; Horizon is for discovering, publishing and collecting Reads.',help:'How to use',portalHelp:'Search and open published Reads. Choose a Read language in Read information (i) while reading.',studioHelp:'Choose a manuscript on the dashboard, edit it in Editor and publish it in Press. Manage Read languages in Project settings.',viewerHelp:'Swipe or use the arrows to turn pages. Tap the center to show controls. Display changes the reading view; Read information (i) contains Read details and languages.',separate:'Navigation stays in this window. Save your manuscript before leaving Studio.',file:'Open a file on this device',home:'Dashboard',editor:'Editor',press:'Press',works:'Reads',guide:'Studio help',development:'Updates are not checked in development previews.'}};
export function initializePlatformMenu({surface,triggers=[],beforeOpen=()=>{},onClose=()=>{},onStudioHome,onFile,fileButton,onHelp,beforeNavigate=()=>true,roomActions=[]}) {
    const dialog=document.createElement('dialog');dialog.className='platform-menu';dialog.id='platform-app-menu';dialog.setAttribute('aria-labelledby','platform-menu-heading');
    dialog.innerHTML='<header><h2 id="platform-menu-heading"></h2><button type="button" data-close>×</button></header><nav aria-label="DSF"></nav><p data-navigation-note></p><details open><summary data-copy="settings"></summary><label for="platform-menu-language"><span data-copy="language"></span></label><select id="platform-menu-language" data-language></select><p data-copy="languageHelp"></p><label for="platform-menu-theme"><span data-copy="theme"></span></label><select id="platform-menu-theme" data-theme></select></details><details><summary data-copy="help"></summary><p data-surface-help></p><h3 data-copy="glossary"></h3><p data-copy="glossaryHelp"></p></details><div id="platform-app-version"><p data-copy="development"></p></div>';
    const navigate=createPlatformNavigator({beforeNavigate});
    const nav=dialog.querySelector('nav');
    for(const [area,href,icon] of [['portal','/','explore'],['studio','/studio?room=home','edit'],['viewer','/viewer','auto_stories']]){
        const local=area===surface,el=document.createElement(local||area==='studio'&&onStudioHome?'button':'a');
        if(el.tagName==='A'){el.href=href;el.addEventListener('click',event=>{if(event.button!==0||event.ctrlKey||event.metaKey||event.shiftKey||event.altKey)return;event.preventDefault();dialog.close();void navigate(href);});}
        else{el.type='button';el.onclick=()=>{dialog.close();if(area==='studio')onStudioHome?.();};}
        if(local)el.setAttribute('aria-current','page');el.innerHTML=`<span class="material-icons" aria-hidden="true">${icon}</span><span data-copy="${area}"></span>`;nav.append(el);
    }
    if(onFile){const file=fileButton||document.createElement('button');file.type='button';file.className='platform-menu-file';file.removeAttribute('onclick');file.dataset.copy='file';file.onclick=()=>{dialog.close();onFile();};nav.append(file);}
    if(roomActions.length){const rooms=document.createElement('nav');rooms.setAttribute('aria-label','Studio');for(const action of roomActions){const button=document.createElement('button');button.type='button';button.dataset.copy=action.room;button.onclick=()=>{dialog.close();action.run();};rooms.append(button);}dialog.querySelector('[data-surface-help]').after(rooms);}
    if(onHelp){const button=document.createElement('button');button.type='button';button.dataset.copy='guide';button.onclick=()=>{dialog.close();onHelp();};dialog.querySelector('[data-surface-help]').after(button);}
    const language=dialog.querySelector('[data-language]'),theme=dialog.querySelector('[data-theme]');language.replaceChildren(...UI_LANGUAGES.map(item=>new Option(item.label,item.code)));
    theme.replaceChildren(...['device','light','dark'].map(value=>new Option(value,value)));
    let lastTrigger;
    function refresh(){const lang=getPlatformLanguage(surface),text=copy[lang];dialog.querySelector('h2').textContent=text.title;dialog.querySelector('[data-close]').setAttribute('aria-label',text.close);for(const el of dialog.querySelectorAll('[data-copy]'))el.textContent=text[el.dataset.copy];dialog.querySelector('[data-surface-help]').textContent=text[surface+'Help'];dialog.querySelector('[data-navigation-note]').textContent=surface==='portal'?'':text.separate;language.value=lang;theme.value=getThemeMode();for(const option of theme.options)option.textContent=text[option.value];for(const trigger of triggers)trigger.setAttribute('aria-label',text.title);}
    function close(){dialog.close();}
    for(const trigger of triggers){trigger.removeAttribute('onclick');trigger.setAttribute('aria-haspopup','dialog');trigger.setAttribute('aria-controls',dialog.id);trigger.setAttribute('aria-expanded','false');trigger.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();beforeOpen();lastTrigger=trigger;refresh();dialog.showModal();trigger.setAttribute('aria-expanded','true');},true);}
    language.onchange=()=>{setPlatformLanguage(language.value);refresh();};theme.onchange=()=>{setThemeMode(theme.value);refresh();};
    dialog.querySelector('[data-close]').onclick=close;
    dialog.addEventListener('click',event=>{event.stopPropagation();const box=dialog.getBoundingClientRect();if(event.target===dialog&&(event.clientX<box.left||event.clientX>box.right||event.clientY<box.top||event.clientY>box.bottom))close();});
    dialog.addEventListener('keydown',event=>event.stopPropagation());dialog.addEventListener('wheel',event=>event.stopPropagation(),{passive:true});
    dialog.addEventListener('close',()=>{for(const trigger of triggers)trigger.setAttribute('aria-expanded','false');lastTrigger?.focus({preventScroll:true});onClose();});
    document.body.append(dialog);subscribePlatformLanguage(refresh);refresh();
    installPlatformLaunchNotice({surface,beforeNavigate});document.dispatchEvent(new Event('dsf-platform-menu-ready'));
    return {refresh,close,get open(){return dialog.open;}};
}
